#include "tests_assembler_parser_instructions/add.hpp"
#include "tests_assembler_parser_instructions/bit_complement.hpp"
#include "tests_assembler_parser_instructions/increment_decrement.hpp"
#include "tests_assembler_parser_instructions/jump.hpp"
#include "tests_assembler_parser_instructions/load.hpp"
#include "tests_assembler_parser_instructions/logical.hpp"
#include "tests_assembler_parser_instructions/machine.hpp"
#include "tests_assembler_parser_instructions/push_pop.hpp"
#include "tests_assembler_parser_instructions/rotation.hpp"
#include "tests_assembler_parser_instructions/set_reset.hpp"
#include "tests_assembler_parser_instructions/shift_swap.hpp"

#include "tests_assembler_parser_instructions/specific.hpp"